# Generated by Django 4.2.13 on 2024-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
